Jdp190501 15
klikuskodilla/project_jdp_1905_01 pull request #1
Opened 2019-06-02 16:53 UTC by AdamSobieraj

2019-06-03 16:24 UTC, godyn reviewed
1. Zmiany w pliku application.properies nie dotyczą bezpośrednio zadania, tylko rozwiązują inny problem.
2. Nie wiem, czy to wskazane dodawać w tym branchu mappera i klasę dto, skoro ich stworzenie jest objęte zadaniami z zakresu 21-25.

2019-06-04 08:28 UTC, erwinMuz requested changes

2019-06-04 08:28 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +                .map(t -> new UsersDto(t.getId(), t.getName(), t.getSurname(),t.geteMailAddress(),t.getUserAddress(), t.getAccountStartDate()))
uzyj metody maptoUserDto

2019-06-04 08:28 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/com/kodilla/ecommercee/domain/Dto/UsersDto.java
> +package com.kodilla.ecommercee.com.kodilla.ecommercee.domain.Dto;
Zly package - com.kodilla.ecommercee.com.kodilla.ecommercee

2019-06-04 08:28 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/com/kodilla/ecommercee/domain/Users.java
> +package com.kodilla.ecommercee.com.kodilla.ecommercee.domain;
Zly package - com.kodilla.ecommercee.com.kodilla.ecommercee

2019-06-05 19:56 UTC, AdamSobieraj commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +                .map(t -> new UsersDto(t.getId(), t.getName(), t.getSurname(),t.geteMailAddress(),t.getUserAddress(), t.getAccountStartDate()))
nie za bardzo rozumiem. Mam wymienic UsersDto na maptoUserDto

2019-06-05 19:57 UTC, AdamSobieraj commented on src/main/java/com/kodilla/ecommercee/com/kodilla/ecommercee/domain/Dto/UsersDto.java
> +package com.kodilla.ecommercee.com.kodilla.ecommercee.domain.Dto;
Jeden i drugi element nie powinien znajdować sie w pod pakietach ?

2019-06-07 13:42 UTC, erwinMuz approved these changes

2019-06-07 19:30 UTC, godyn requested changes
Brak zdefiniowanych relacji względem innych encji.

2019-06-10 20:28 UTC, godyn approved these changes

2019-06-10 21:01 UTC, merged