Jdp190501 20
klikuskodilla/project_jdp_1905_01 pull request #11
Opened 2019-06-13 09:10 UTC by AdamSobieraj

2019-06-13 14:32 UTC, MarcinPekala approved these changes
Cześć, daję approve'a do tego brancha, ale na chyba drugim spotkaniu Karol mówił żeby nie zostawiać wiszących pull requestów. Więc musisz chyba zamknąć albo zmienić https://github.com/klikuskodilla/project_jdp_1905_01/pull/5

2019-06-14 09:55 UTC, erwinMuz requested changes

2019-06-14 09:55 UTC, erwinMuz commented on gradlew
> +    # Add a users-defined pattern to the cygpath arguments
niepotrzebna zmiana

2019-06-14 09:55 UTC, erwinMuz commented on src/test/java/com/kodilla/ecommercee/repositoryDao/UserRepositoryTestSuit.java
> +        assertNotEquals(0.0, orderId1);
Double vs Long?

2019-06-14 15:46 UTC, AdamSobieraj commented on gradlew
> +    # Add a users-defined pattern to the cygpath arguments
? nie rozumiem o co chodzi

2019-06-16 16:03 UTC, erwinMuz requested changes

2019-06-16 16:03 UTC, erwinMuz commented on gradlew
> +    # Add a users-defined pattern to the cygpath arguments
Zrobiles pewenie rename - plik gradlew nie ma potrzeby zmianiac.

2019-06-17 08:58 UTC, erwinMuz approved these changes

2019-06-17 08:59 UTC, merged