JDP190501-16
klikuskodilla/project_jdp_1905_01 pull request #12
Opened 2019-06-13 16:02 UTC by MarcinPekala

Encja Order - Testy

2019-06-13 20:01 UTC, godyn requested changes

2019-06-13 20:01 UTC, godyn commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        Assert.assertNotEquals(order3, findOrder);
Not - a powinny być równe. Ale jak dasz assertEquals to też Cię nie przepuści, bo nie może porównywać Optionala ze zwykłym obiektem. Ten sam błąd zrobiłam w moim teście Group. :) Zauważyłam to pracując nad testami Product. Tam obeszłam to taką asercją: assertTrue(foundProduct.isPersent()). Pytanie tylko, czy to nie za słaby warunek, bo sprawdza tylko istnienie, a nie dokładną zawartość...

2019-06-13 20:01 UTC, godyn commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        order4.setUsers(user2);
Tutaj jest chyba za dużo. Tzn trzeba pokazać, że wiele zamówień może być przypisanych do jednego usera. Więc user1 wystarczy.

2019-06-13 20:01 UTC, godyn commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        userDao.save(user1);
A dlaczego userDao a nie orderRepository.save(order1)?

2019-06-13 20:05 UTC, MarcinPekala commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        userDao.save(user1);
Nie przechodzą testy na orderRepository.save(order1)

2019-06-14 14:02 UTC, MarcinPekala commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        order4.setUsers(user2);
Masz na myśli to że mam w ogóle wywalić user2 z testów?

2019-06-14 18:51 UTC, godyn commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        order4.setUsers(user2);
Tak, uważam że user2 i i operacje na nim są zbędne.

2019-06-14 18:53 UTC, MarcinPekala commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        order4.setUsers(user2);
Okej, dzięki za feedback

2019-06-14 18:56 UTC, godyn commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        userDao.save(user1);
Hm, wydaje mi się, że te testy właśnie na tym mają polegać że używa się w nich i testuje orderRepository, a nie inne dao... Może warto upewnić się u Mentorów?

2019-06-14 19:06 UTC, MarcinPekala commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        userDao.save(user1);
@godyn Okej, jestem za. Próbowałem różnych sposobów ale nie wykombinowałem jak zrobić testy do ManyToOne żeby działały z orderRepository.

2019-06-17 10:24 UTC, godyn requested changes

2019-06-17 10:24 UTC, godyn commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +    private Users user1 = new Users(1234L,"Magda", "Solety", "magda_solety@gmail.com", "Mazowiecka 13, Wrocław", LocalDate.of(2015, 6, 17));
Usera też lepiej wrzucić do Before

2019-06-17 10:24 UTC, godyn commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        Assert.assertEquals(findOrder.get().getOrderId(), order3Id);
Chyba spoko, aczkolwiek jak ja tak zrobiłam, to wystąpił mi warn, że stosuję metodę .get() z Optionala bez sprawdzenia, czy on w ogole istnieje (czy nie jest nullem). I zrobiłam ostatecznie tak:  Assert.assertTrue(groupFound.isPresent() && groupFound.get().getGroupId().equals(group4Id));
Ale może to co Ty masz wystarczy...

2019-06-17 10:24 UTC, godyn commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +    Assert.assertNotEquals(0.0, orderId);
Porównujesz double vs Long. Jeśli zamiast 0.0 dasz bezpośrednio w metodzie 0L to utworzy Ci longa, a Ty potrzebujesz Longa (wrappera). Dlatego trzeba wprowadzić zmienną np Long nullId = 0L i tą zmienną posługiwać się w asercjach

2019-06-17 10:24 UTC, godyn commented on src/test/java/com/kodilla/ecommercee/repositoryDao/OrderRepositoryTestSuite.java
> +        Assert.assertNotEquals(0.0, userId1);
jak wyżej

2019-06-18 14:07 UTC, closed without merging