Jdp190501 2
klikuskodilla/project_jdp_1905_01 pull request #23
Opened 2019-06-20 19:23 UTC by MarcinPekala

2019-06-21 08:12 UTC, godyn commented
Adam wprowadził folder na klasy Dto, widać to w jego PR:
src/main/java/com/kodilla/ecommercee/domain/Dto/UsersDto.java
Czy mógłbyś też utworzyć ten folder u siebie i do niego przenieść GroupDto?

2019-06-21 12:52 UTC, godyn approved these changes

2019-06-21 16:00 UTC, erwinMuz requested changes

2019-06-21 16:00 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public void createGroup(GroupDto groupDto) {
Brak @requestbody

2019-06-21 16:00 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public GroupDto updateGroup(GroupDto groupDto) {
Brak @requestbody

2019-06-21 16:00 UTC, erwinMuz commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public GroupDto getGroup(Long groupId) throws GroupNotFoundException {
Brak RequestParam

2019-06-22 20:10 UTC, PTrostowiecki approved these changes
dla mnie wydaje sie byc ok

2019-06-23 08:26 UTC, erwinMuz approved these changes

2019-06-23 13:49 UTC, merged