Jdp190501 5
klikuskodilla/project_jdp_1905_01 pull request #5
Opened 2019-06-05 16:52 UTC by AdamSobieraj

2019-06-07 18:39 UTC, godyn commented on src/main/java/com/kodilla/ecommercee/service/DbService.java
> +public class DbService {
Każda encja będzie miała swój serwis, więc proponuję żebyśmy nadawali bardziej specyficzne nazwy, np UserDbService

2019-06-12 15:02 UTC, MarcinPekala requested changes
Cześć, dto, serwis i mapper powinny iść do brancha z taska: JDP190501-25. 
"Dodaj rzeczywistą implementację metod w tym kontrolerze.
Utwórz serwis, mapper i dto. Jeśli zmodyfikujesz repozytorium, koniecznie napisz nowe testy."

2019-06-21 09:58 UTC, godyn approved these changes

2019-06-21 09:58 UTC, godyn commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "/getUsers/{id}")
Nie wiem czy ten slash (/) na początku value robi jakąś różnicę, czy jest problemem, czy nie (w metodzie wyżej go nie ma, a w pozostałych zaczynasz od slasha.

2019-06-21 09:58 UTC, godyn commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +
W tym brachu dodajesz UserNotFoundException, więc już może warto dopisać jego wyrzucenie w metodzie, w której planowałeś się nim posłużyć.

2019-06-21 20:27 UTC, godyn requested changes

2019-06-21 20:27 UTC, godyn commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +
Jeszcze adnotacje @RequestParam i @RequestBody

2019-06-22 08:12 UTC, godyn approved these changes

2019-06-22 16:13 UTC, PTrostowiecki approved these changes
dla mnie wyglada ok

2019-06-22 20:01 UTC, MarcinPekala approved these changes
wszystko ok

2019-06-23 07:30 UTC, merged